chore: upgrade misspell Docker stage
- from alpine 3.12 to 3.13
- from curl 7.69.1-r1 to 7.74.0-r1

as otherwise build fails with:

```
Step 8/33 : RUN apk add --no-cache curl==7.69.1-r1 &&     curl -L -o ./install-misspell.sh https://git.io/misspell &&     sh ./install-misspell.sh
 ---> Running in 076b1199566d
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  curl-7.69.1-r3:
    breaks: world[curl=7.69.1-r1]
```